sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t justinwang/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true justinwang/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-777708073040"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY



